version: 1
disable_existing_loggers: False
formatters:
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
  file_api:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: ../logs/api/api.log
    maxBytes: 10485760
    backupCount: 5
  file_audit:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: ../logs/audit/audit.log
    maxBytes: 10485760
    backupCount: 10
loggers:
  app:
    level: INFO
    handlers: [console, file_api]
    propagate: no
  audit:
    level: INFO
    handlers: [console, file_audit]
    propagate: no
root:
  level: WARNING
  handlers: [console]
